# Generated by Django 6.0.5 on 2026-06-11 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
